name: Code check

on:
  pull_request:
    branches: [develop, master]

jobs:
  code_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Check black
        run: black .
      
      - name: Check flake8
        run: flake8
      
      - name: Run test
        run: |
          pytest -vv --cov=app --junitxml=pytest.xml --cov-report=term-missing | tee pytest-coverage.txt
      
      - name: Check test coverage
        run: |
          coverage_threshold=80
          coverage_result=$(awk -F " " '/^TOTAL/ {print substr($NF, 1, length($NF)-1)}' pytest-coverage.txt)
          if (( $(echo "$coverage_result < $coverage_threshold" | bc -l) )); then
            echo "Test coverage is below the threshold ($coverage_result%). Blocking PR merge."
            exit 1
          fi

          
